### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by satomma** [andrea-mattioli/mattiols_hassio_repository#28]
Ho provato più volte, cambiando chiave e verificando le configurazioni che sembrano tutte corrette ma ricevo sempre questo errore quando cerco di verificare le API di Legrand.
Il registro riporta questo errore:
`[2021-05-04 21:36:31,688] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "bticino.py", line 299, in get_plants
    plants = json.loads(response.text)['plants']
KeyError: 'plants'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 744, in callback
    my_plants=get_plants(access_token)
  File "bticino.py", line 307, in get_plants
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'KeyError' object has no attribute 'errno'`

Non so come procedere oltre..

**Comment by andrea-mattioli** [comment]
hai abilitato l'accesso terze parti sull'app ufficiale bticino dello smarter?

**Comment by satomma** [comment]
Mancava proprio quello.. sono giorni che cambio e riferisco chiavi ecc.. avevo disattivato per sbaglio l'accesso.
Grazie

**Comment by umby63** [comment]
io ho lo stesso errore: "This is a development server"  e anche "[2023-12-23 19:09:04,230] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 299, in get_plants
    plants = json.loads(response.text)['plants']
             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'plants'
come procedo ? grazie
