### ISSUE TITLE
Errore Installazione

### ISSUE THREAD

**Issue by CeccoCQ** [andrea-mattioli/mattiols_hassio_repository#30]
Ciao Andrea,
ho riscontrato questo errore all'avvio del add-on.

```
[12:40:42] INFO: Init Smarter file ...
[12:40:42] INFO: 64bit Version detected
[12:40:42] INFO: Setup config file...
[12:40:45] INFO: Trying autologin to Legrand...
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/hassio_bticino_smarter/login.py", line 20, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
[cmd] /hassio_bticino_smarter/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Hai qualche idea?

**Comment by andrea-mattioli** [comment]
prova a fare rebuild dell'addon

**Comment by CeccoCQ** [comment]
Ok grazie Andrea, sembra funzionare!
Una domanda, dopo un pò di tempo sembra che i sensori non si aggiornino più e ogni volta sono costretto a rifare "get code", è un comportamento normale oppure c'è qualcosa che non va?

**Comment by andrea-mattioli** [comment]
controlla i log di HA, non ho avuto altre segnalazioni in merito
