### ISSUE TITLE
Addon non si avvia

### ISSUE THREAD

**Issue by ilpiccoli** [andrea-mattioli/mattiols_hassio_repository#35]
Ciao, ho disinstallato la V1, cancellato tutti i file, seguito le procedure per creare i nuovi codici sul sito di BTicino e ho configurato l'addon.. nonostante questo non partiva e dopo qualche secondo si arrestava da solo.
Ho provato a disinstallare tutto e re-installare ma niente, nei log appare questo.. cosa posso fare?
Grazie in anticipo
```

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:55:01] INFO: Smarter file already exist and contain some data.
[14:55:01] INFO: Setup config file...
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 674, in <module>
    schedule_update_token()
  File "/hassio_bticino_smarter/bticino.py", line 672, in schedule_update_token
    scheduler.add_job(f_refresh_token, 'interval', minutes=50)
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/lib/python3.9/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/lib/python3.9/site-packages/apscheduler/util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "/hassio_bticino_smarter/mqtt.py", line 5, in <module>
    from bticino import send_thermostat_cmd, load_api_config_arg
  File "/hassio_bticino_smarter/bticino.py", line 674, in <module>
    schedule_update_token()
  File "/hassio_bticino_smarter/bticino.py", line 672, in schedule_update_token
    scheduler.add_job(f_refresh_token, 'interval', minutes=50)
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/lib/python3.9/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/lib/python3.9/site-packages/apscheduler/util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
[cmd] /hassio_bticino_smarter/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by andrea-mattioli** [comment]
devi installare la v2

**Comment by ilpiccoli** [comment]
Sisi, ho disinstallato la V1, installato la V2 e mi da quell'errore

**Comment by andrea-mattioli** [comment]
puoi provare a:

1.  Rimuovere l'addon
2.  Ricaricare la raccolta dei componenti aggiuntivi dall'apposito tasto "ricarica"
3.  Installare l'addon v2

**Comment by ilpiccoli** [comment]
Ora sembra funzionare, si avvia correttamente e da web browser riesco a vedere i dati, che coincidono con quelli che vedo da app, ho seguito il procedimento per creare le entità tramite package e si sono create, però non si aggiornano, nemmeno riavviando o ricostruendo l'addon

**Comment by andrea-mattioli** [comment]
arrivano delle post in automatico, se non ti arrivano hai  problemi di routing oppure hai fatto male l'app su legrand
