### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by MatteoGhittorelli** [andrea-mattioli/mattiols_hassio_repository#4]
Dear Andrea, 
I'm trying to configure the Smarter Add-on, but I always obtain an internal server error. Here the log:

188.216.212.33 - xxx@gmail.com [08/Aug/2020:12:11:21 +0200] "GET / HTTP/1.1" 200 876 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"
[2020-08-08 12:11:29,554] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "bticino.py", line 221, in get_plants
    plants = json.loads(response.text)['plants']
KeyError: 'plants'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 574, in callback
    my_plants=get_plants(access_token)
  File "bticino.py", line 227, in get_plants
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'KeyError' object has no attribute 'errno'

How can I solve this issue? Thanks a lot

**Comment by andrea-mattioli** [comment]
Hi Matteo,
check you configuration, this error happens when 
client_id or client_secret or subscription_key mismatch.

**Comment by MatteoGhittorelli** [comment]
Hi Andrea, 
  I double checked my configuration and it is ok. How can I solve this problem?
Thanks !

**Comment by andrea-mattioli** [comment]
Hi Matteo, please send me a private message on skype andrea.mattiols or andrea.mattiols@gmail.com.
