### ISSUE TITLE
Addon non invia comandi

### ISSUE THREAD

**Issue by Steve707-AE** [andrea-mattioli/mattiols_hassio_repository#45]
Quando provo ad aumentare il setpoint dal lovelace poi riaggiornando la pagina ritorna a quello precedente, come se non avesse cambiato nulla, lo stesso se provo direttamente a mandare un comando mqtt, in ascolto va bene, infatti se aumento dall'app poi aumenta anche nella card, ma da homeassistant non fa nulla, ho provato a fare già il rebuild dell'addon..

**Comment by Steve707-AE** [comment]
Vorrei avere risposta, grazie..

**Comment by Steve707-AE** [comment]
[2022-01-31 01:41:58,079] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hassio_bticino_smarter/bticino.py", line 742, in callback
    access_token, refresh_token = get_access_token(code)
  File "/hassio_bticino_smarter/bticino.py", line 268, in get_access_token
    access_token = json.loads(response.text)['access_token']
KeyError: 'access_token'
192.168.0.12 - - [31/Jan/2022 01:41:58] "GET /callback?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..dMoolMdMrrPJqNce.GGyNzhP_Xmmy9h5hdNyEuWkf1etaFIctTZQ9uxJjMVv_EdK3ZxpPT93S0dE7t1Z6X2Zby-eMZ7yZ2FxNvXWQONknfvRGpivCUIkmOJ6AR2ofKdoznZgw-ibfny_aXLTjXixmDE0JIzrP2oMn-_l2BRm5u11ntKM9uTtS27I0oizw2tvAzgNsUjzD25kOvJVGW7hRDxRop9rNcpij2Zp0btZnOXdsAH-Jwj_hXs8zn3CqTLauvdjs9hboS2hWUnF35s29llCZ3T3asnj5sRUIHb3f-BG1yJadU9wotLmDOSiJmd6gb5kE4W8gguM-Yj4aGx4b5hHwYOijHvrhV5NLSbtuhpq13ylqhFVoxVMUJZEBikfb8q20KSKhA65RqIniAfgngHfvQVJjgCgO1jnOl3pCAK1m2RVQzfMdZKUMuLf3BCyHUivWjpBJfn3ZvH7EIyBj8_J-aXlLkt9jnt1kAM8z4bOZmXHKZmLbFIIIYPpedw1SFvAcadpJYffjj9cj3MT9qMUJbihQn24-fKDWlUNhWww1jp0IXHOwaf1j-GZfzAszCG7pVSyREWKNjzuYUB6XbW7OLXoJyBbZpOWd6W8UgNWapvv7TREX0_fkUG6fi5cr2GCrpapdpIxnuf8yyWJ5H3o6SlDCbhM4gy6ptRmza6J5w9SdxzAkHA-ddLjvXW4nikg5ghT6kgT3srQQzoz-ItDPIWvUbcxJZmaS9JizdHfRZbpXurTDdiMlsVYuREVBZ-s5pZwhnDVsMr1hKq0ng_1D2OJPh2I0C6kSNt-oPJ3RaIda6EOq2_ZILuiqkEW26dqWyui72__2YH1iwMDW4D2LzeZ_8PCDjGPtfnjIrfHjf-0-Tb026NNCMXZUPKgK0M0BpWXiaMrgXw.N_EOtTQhKe9Z1dDQX8RUTw&state=VD6DroK87AJKx7OWFPXnZAE1MRPYbCe6 HTTP/1.1" 500 -

**Comment by andrea-mattioli** [comment]
Quale versione dell'addon stai usando v1 o v2?
prova a rimuovere la directory config/.bticino_smarter e fare il rebuild dell'addon

**Comment by Steve707-AE** [comment]
La v2, ora lo faccio e vedo

**Comment by Steve707-AE** [comment]
Allora ho rifatto il rebuild, e per qualche giorno va, ma dopo improvvisamente crasha e non invia più comandi. Devo andare sulla pagina web e ricollegare l'account bticino, fatto ciò vedo le informazioni ma non invia i comandi...

**Comment by andrea-mattioli** [comment]
che configurazione usi su virtual machine, scrivi su SD o ssd?
Per me non riesce a scrivere ogni tanto su disco, se vedi dentro la directory che ti ho detto sopra ci sono dei file che aggiorna ogni tot con dei token che prende da legrand, se non trova il file o il token non è valido non invia comandi...

**Comment by Steve707-AE** [comment]
Scrivo su micro sd, con raspberry e HASSIO. Ieri ho fatto il rebuild e non li invia lo stesso..

**Comment by andrea-mattioli** [comment]
rimuovi la directory nuovamente e fail il restart e posta i log del boot dell'addon.

**Comment by Steve707-AE** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:51:42] INFO: Smarter file already exist and contain some data.
[16:51:42] INFO: Setup config file...
 * Serving Flask app "bticino" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on *** (Press CTRL+C to quit)
****- - [16/Feb/2022 16:52:06] "GET / HTTP/1.1" 200 -
***** - - [16/Feb/2022 16:52:24] "GET /info HTTP/1.1" 200 -
***** - - [16/Feb/2022 16:53:07] "GET / HTTP/1.1" 200 -
**** - - [16/Feb/2022 16:54:27] "GET /callback?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..c0pKClGkLEP3H_oP.zQckz0Li7D8lXc6tXvI5vUAbVbWicV74BuhqqyqXSq9P9cucjpKAjnXv826cgW4JNKg4l9iZfm9XoyMSQEJ2Hm5rtCaIoxO2LXekIzjG4qAjXJtK-YQ10DVAEAdPTVl50zX5VBVdDAmFbjTYB4wN65AmmBZK6pd-jXjXn5dGOaxb9Gd52MYiBHI0Y4GK1NwJui4qcP_CN7IpAcc8tbuGq8N5lX82OCuLllVZ5Uznxpn6Kjj2RZOsB302GOI6uqy5CZT8g5vJNPJ-Mlue7_sHNdCrby3K14mFQvwb5XWLrq0lXJ5GLpfFiKkp1JhvWPeGGPu_Gh8BBiHsFj3aL-o4w3lwUxPa_i8vTRuoLaOcGxz7FsMALA8Qr-VNj5bJpc4FkvR6MmBSMCaRI6Q0hrmPGLAVKMixeW0qk6pG9vDVQ4zJxNxRC_BoKTgPYU3TiqnlE-DmTXxL66nW5bDCcTNtC2f7RuhYKoESqybaLKJzn54Sx2t7DHj4_f_ZrUOl18knDsu3emyH2VDKpxv16nCZIUzhNpxJN4cpUvm4S8GvYfrnG3Xn0MYGf97tcp1RBBfSNVpCKnOkiy8aEcDCOrHff7JEHgQytPezes1oFlO3hC--urX_MCdPnd1EtkOYBnwWLbA64NxIgWuTs_KBZB9GQr1HJb9JHkx__IMrokUhc7y9WvIww4mRQHSgzvFPtC0idlmiyB1wXNUYneARUmmg9-YjlpcoNZtHlTvvHmNgsRkKtZ0BJiJkF0t2L9fl2yj1YddsOFxFaSk5_1VzHKPKUaz6D11XK-jKa2o0cCpcAezcK0H_e1Y5Ke4CXJQMPbw25qa6KcedXjy_-_sEgV4Og-YE3qPPwZ93ipEWBQ53oHjP5T031PwEBbk.OODDSQ7C34XRKo66dV_lKQ&state=zKJy8yaUwzsYuJ4JCNECGAkBqFLGLCWr HTTP/1.1" 200 -

Ecco qua dice questo

**Comment by andrea-mattioli** [comment]
NON hai rimosso la directory come ti avevo detto altrimenti questo log non sarebbe comparso:
[16:51:42] INFO: Smarter file already exist and contain some data.

Sarebbe dovuto comparire:
[XX:XX:XX] INFO: Init Smarter file ...

**Comment by andrea-mattioli** [comment]
Close for inactivity
