### ISSUE TITLE
Failed to to call /addons/d5113cf9_smarter_x8000_v2/stats - Container addon_d5113cf9_smarter_x8000_v2 is not running

### ISSUE THREAD

**Issue by Epas98** [andrea-mattioli/mattiols_hassio_repository#51]
ciao Andrea, spero che mi potrai aiutare e 2 giorni che cerco di configurare la integrazione ma non riesco a venirci a capo.
Questo e l'errore che ricevo:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[00:21:43] INFO: Smarter file already exist and contain some data.
[00:21:43] INFO: Setup config file...
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 1, in <module>
    from flask import  Flask,jsonify,request,session,redirect,render_template,url_for,send_from_directory,Response
  File "/usr/lib/python3.9/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/lib/python3.9/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/lib/python3.9/site-packages/itsdangerous/__init__.py)
Traceback (most recent call last):
  File "/hassio_bticino_smarter/mqtt.py", line 5, in <module>
    from bticino import send_thermostat_cmd, load_api_config_arg
  File "/hassio_bticino_smarter/bticino.py", line 1, in <module>
    from flask import  Flask,jsonify,request,session,redirect,render_template,url_for,send_from_directory,Response
  File "/usr/lib/python3.9/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/lib/python3.9/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/lib/python3.9/site-packages/itsdangerous/__init__.py)
[cmd] /hassio_bticino_smarter/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Uso duckdns e il tuo Mattiols Reverse Proxy.

Grazie mille

**Comment by andrea-mattioli** [comment]
molto strano, sembra come se non si fosse correttamente eseguita la build del container.
potresti provare ad andare su http://tuoip:8123/hassio/store e fare controlla aggiornamenti.
cancella poi la directory ".bticino_smarter" dentro config e rilanciare il rebuild del container.

**Comment by andrea-mattioli** [comment]
Close for inactivity
