### ISSUE TITLE
Cannot install netatmo on home assistant (I'm using a smarther x8000)

### ISSUE THREAD

**Issue by Simonik71** [andrea-mattioli/mattiols_hassio_repository#62]
Logger: homeassistant.config_entries
Source: components/netatmo/data_handler.py:199
First occurred: 12:23:25 (1 occurrences)
Last logged: 12:23:25

Error setting up entry Home Assistant Cloud for netatmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 164, in async_setup_entry
    await data_handler.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 151, in async_setup
    await self.subscribe(ACCOUNT, ACCOUNT, None)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 243, in subscribe
    await self.async_fetch_data(signal_name)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 199, in async_fetch_data
    await getattr(self.account, self.publisher[signal_name].method)(
  File "/usr/local/lib/python3.10/site-packages/pyatmo/account.py", line 69, in async_update_topology
    self.process_topology()
  File "/usr/local/lib/python3.10/site-packages/pyatmo/account.py", line 58, in process_topology
    self.homes[home_id] = Home(self.auth, raw_data=home)
  File "/usr/local/lib/python3.10/site-packages/pyatmo/home.py", line 48, in __init__
    self.modules = {
  File "/usr/local/lib/python3.10/site-packages/pyatmo/home.py", line 49, in <dictcomp>
    module["id"]: getattr(modules, module["type"])(
AttributeError: module 'pyatmo.modules' has no attribute 'Z3L'

**Comment by Simonik71** [comment]
Could you provide a video ? The instructions seems not clear... I cannot use your component :(
